name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Rust project
        run: cargo build --release
        
      - name: Copy documentation
        run: mkdir -p docs
              
      - name: Generate documentation
        run: cargo doc --target-dir docs --no-deps

      - name: Prepare Index.html
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=build_wheel\">" > docs/doc/index.html
      

      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          provider: pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs
