name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    if: github.repository == 'rust-lang/rust-analyzer'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup update --no-self-update stable

      - name: Make directory
        run: mkdir -p docs

      - name: Generate documentation
        run: cargo doc --target-dir docs --all --no-deps

      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          provider: pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs
