name: Documentation

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --document-private-items

      - name: Generate index.html file
        run: |
          echo "<meta http-equiv=refresh content=0;url=wasm_oidc_plugin/index.html>" > target/doc/index.html

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: target/doc

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs

      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          folder: docs
          branch: gh-pages
