name: Generate and Deploy Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust project
        run: cargo build --release

      - name: Generate documentation
        run: cargo doc --target-dir docs --no-deps

      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          provider: pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs
